### ISSUE TITLE
Something wrong in train.py line 396 "wav_spec = val_data.inverse_spec(gs[:, :, :, :mel_len[0]].detach(), stft)"

### ISSUE THREAD

**Issue by Zhengyan-Sheng** [ms-dot-k/Visual-Context-Attentional-GAN#2]
Traceback (most recent call last):
  File "train.py", line 479, in <module>
    train_net(args)
  File "train.py", line 122, in train_net
    _ = validate(v_front, gen, post, fast_validate=True)
  File "train.py", line 396, in validate
    wav_spec = val_data.inverse_spec(gs[:, :, :, :mel_len[0]].detach(), stft)
  File "XXXX/vid_aud_grid.py", line 216, in inverse_spec
    wav = griffin_lim(spec.squeeze(1), stft.stft_fn, 60).squeeze(1)  # B,L
  File "XXXX/audio_processing.py", line 63, in griffin_lim
    signal = stft_fn.inverse(magnitudes, angles).squeeze(1)
  File "XXXX/Visual-Context-Attentional-GAN/src/data/stft.py", line 108, in inverse
    padding=0)
RuntimeError: Given transposed=1, weight of size [1026, 1, 1024], expected input[44, 642, 298] to have 1026 channels, but got 642 channels instead

**Comment by ms-dot-k** [comment]
I have changed the src.data.vid_aud_grid.py.
There was a mismatch between hyperparameters.
